name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install
    - name: Install Dependencies
      run: npm install

    # 4. Test
    - name: Run Tests
      run: npm test

    # 5. Security Scan
    - name: Security Scan
      run: npm audit --audit-level=high

    # 6. Docker Login
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 7. Build Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .

    # 8. Push Image
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

    # 9. Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 3000:3000 --name app ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

    # 10. Notify
    - name: Done
      run: echo "Deployment Successful 🚀"